### ISSUE TITLE
Make the Sticker Pack exportable into Telegram

### ISSUE THREAD

**Issue by francescomazzini** [STICKEREST/stickerest#38]

**Comment by HexagonNico** [comment]
Stickers pack that are already uploaded on Telegram can be added by opening the URL "https://telegram.me/addstickers/<PackName>".

See examples in 6e2ca24b4018cc85bb061b62e8df4fdbf8753e9b

Telegram bot created at [StickerestBot](http://t.me/StickerestBot)

The bot API can be used to import stickers into Telegram. See [Stickers](https://core.telegram.org/api/stickers).
Still needs to be implemented in the app.

The API requires a private key added in `api_keys.js`, which is added to `.gitignore`.

**Comment by HexagonNico** [comment]
Telegram API implemented in [api/Telegram.tsx](https://github.com/STICKEREST/stickerest/blob/telegram-api/code/api/Telegram.tsx)
